{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f0c30309-c741-43e9-a340-f06bc3c50c12",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: streamlit in c:\\programdata\\anaconda3\\lib\\site-packages (1.37.1)\n",
      "Requirement already satisfied: pandas in c:\\programdata\\anaconda3\\lib\\site-packages (2.2.2)\n",
      "Requirement already satisfied: matplotlib in c:\\programdata\\anaconda3\\lib\\site-packages (3.9.2)\n",
      "Requirement already satisfied: seaborn in c:\\programdata\\anaconda3\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (24.1)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (4.25.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: watchdog<5,>=2.1.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from streamlit) (4.0.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\programdata\\anaconda3\\lib\\site-packages (from pandas) (2023.3)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib) (3.1.2)\n",
      "Requirement already satisfied: jinja2 in c:\\programdata\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: toolz in c:\\programdata\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: six>=1.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit pandas matplotlib seaborn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fa4005ab-8cf6-4e62-8cf0-6de884b730dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-19 15:07:21.361 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-05-19 15:07:21.361 Session state does not function when running a script without `streamlit run`\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Cargar el dataset\n",
    "df = pd.read_csv('data.csv')\n",
    "df['Date'] = pd.to_datetime(df['Date'])\n",
    "\n",
    "st.title('Análisis Visual de Ventas de Tienda de Conveniencia')\n",
    "st.sidebar.header('Filtros')\n",
    "\n",
    "# Filtro por Sucursal\n",
    "branches = df['Branch'].unique()\n",
    "selected_branch = st.sidebar.selectbox('Seleccionar Sucursal', ['Todas'] + list(branches))\n",
    "if selected_branch != 'Todas':\n",
    "    df_filtered = df[df['Branch'] == selected_branch]\n",
    "else:\n",
    "    df_filtered = df.copy()\n",
    "\n",
    "# Filtro por Línea de Producto\n",
    "product_lines = df_filtered['Product line'].unique()\n",
    "selected_product_line = st.sidebar.selectbox('Seleccionar Línea de Producto', ['Todas'] + list(product_lines))\n",
    "if selected_product_line != 'Todas':\n",
    "    df_filtered = df_filtered[df_filtered['Product line'] == selected_product_line]\n",
    "\n",
    "st.subheader('Evolución de las Ventas Totales')\n",
    "sales_over_time = df_filtered.groupby('Date')['Total'].sum().reset_index()\n",
    "fig_sales_time, ax_sales_time = plt.subplots(figsize=(10, 5))\n",
    "sns.lineplot(x='Date', y='Total', data=sales_over_time, ax=ax_sales_time)\n",
    "ax_sales_time.set_title('Evolución de las Ventas Totales a lo Largo del Tiempo')\n",
    "ax_sales_time.set_xlabel('Fecha')\n",
    "ax_sales_time.set_ylabel('Ventas Totales')\n",
    "plt.xticks(rotation=45)\n",
    "st.pyplot(fig_sales_time)\n",
    "\n",
    "st.subheader('Ingresos por Línea de Producto')\n",
    "product_line_sales = df_filtered.groupby('Product line')['Total'].sum().sort_values(ascending=False)\n",
    "fig_product_sales, ax_product_sales = plt.subplots(figsize=(10, 5))\n",
    "sns.barplot(x=product_line_sales.index, y=product_line_sales.values, ax=ax_product_sales)\n",
    "ax_product_sales.set_title('Ingresos por Línea de Producto')\n",
    "ax_product_sales.set_xlabel('Línea de Producto')\n",
    "ax_product_sales.set_ylabel('Ingresos Totales')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "st.pyplot(fig_product_sales)\n",
    "\n",
    "st.subheader('Distribución de la Calificación de Clientes')\n",
    "fig_rating, ax_rating = plt.subplots(figsize=(8, 5))\n",
    "sns.histplot(df_filtered['Rating'], bins=10, kde=True, ax=ax_rating)\n",
    "ax_rating.set_title('Distribución de la Calificación de Clientes')\n",
    "ax_rating.set_xlabel('Calificación')\n",
    "ax_rating.set_ylabel('Frecuencia')\n",
    "st.pyplot(fig_rating)\n",
    "\n",
    "st.subheader('Comparación del Gasto por Tipo de Cliente')\n",
    "fig_customer_type, ax_customer_type = plt.subplots(figsize=(8, 5))\n",
    "sns.boxplot(x='Customer type', y='Total', data=df_filtered, ax=ax_customer_type)\n",
    "ax_customer_type.set_title('Comparación del Gasto por Tipo de Cliente')\n",
    "ax_customer_type.set_xlabel('Tipo de Cliente')\n",
    "ax_customer_type.set_ylabel('Gasto Total')\n",
    "st.pyplot(fig_customer_type)\n",
    "\n",
    "st.subheader('Relación entre Costo y Ganancia Bruta')\n",
    "fig_cogs_income, ax_cogs_income = plt.subplots(figsize=(8, 5))\n",
    "sns.scatterplot(x='cogs', y='gross income', data=df_filtered, ax=ax_cogs_income)\n",
    "ax_cogs_income.set_title('Relación entre Costo de Bienes Vendidos e Ingreso Bruto')\n",
    "ax_cogs_income.set_xlabel('Costo de Bienes Vendidos (cogs)')\n",
    "ax_cogs_income.set_ylabel('Ingreso Bruto (gross income)')\n",
    "st.pyplot(fig_cogs_income)\n",
    "\n",
    "st.subheader('Métodos de Pago Preferidos')\n",
    "payment_counts = df_filtered['Payment'].value_counts()\n",
    "fig_payment, ax_payment = plt.subplots(figsize=(8, 5))\n",
    "ax_payment.pie(payment_counts, labels=payment_counts.index, autopct='%1.1f%%', startangle=140)\n",
    "ax_payment.set_title('Métodos de Pago Preferidos')\n",
    "st.pyplot(fig_payment)\n",
    "\n",
    "st.subheader('Composición del Ingreso Bruto por Sucursal y Línea de Producto')\n",
    "branch_product_income = df_filtered.groupby(['Branch', 'Product line'])['gross income'].sum().unstack()\n",
    "fig_branch_product, ax_branch_product = plt.subplots(figsize=(10, 6))\n",
    "branch_product_income.plot(kind='bar', stacked=True, ax=ax_branch_product)\n",
    "ax_branch_product.set_title('Composición del Ingreso Bruto por Sucursal y Línea de Producto')\n",
    "ax_branch_product.set_xlabel('Sucursal')\n",
    "ax_branch_product.set_ylabel('Ingreso Bruto')\n",
    "ax_branch_product.tick_params(axis='x', rotation=0)\n",
    "ax_branch_product.legend(title='Línea de Producto')\n",
    "st.pyplot(fig_branch_product)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8baf93d4-08ec-4bc1-8edb-1d2675527cf7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
